### ISSUE TITLE
V2Ray和Trojan不能共存

### ISSUE THREAD

**Issue by iDaming** [missuo/XrayR-V2Board#11]
系统：CentOs7
logs如下：
XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Unit XrayR.service entered failed state.
XrayR.service failed.
XrayR.service holdoff time over, scheduling restart.
Stopped XrayR Service.
Started XrayR Service.
XrayR 0.8.0 (A Xray backend that supports many panels)

**Comment by missuo** [comment]
请问你在运行 XrayR 之前，是否已经在面板添加节点呢？
