### ISSUE TITLE
我按照规定做了一切。V2ray和shadowsocks节点为蓝色，而木马为红色（不起作用）

### ISSUE THREAD

**Issue by GoodyOG** [missuo/XrayR-V2Board#12]

**Comment by missuo** [comment]
木马是什么？

**Comment by missuo** [comment]
我看了你的Repo，配置都正常。木马是指什么？你用的客户端是什么？

**Comment by GoodyOG** [comment]
我正在使用 V2rayNG 在安卓上

**Comment by missuo** [comment]
你选择了Trojan，需要自行配置证书。建议你改成v2ray TLS不启用

**Comment by GoodyOG** [comment]
非常感谢您的快速回复。V2ray是我的主要用途。以防万一我想使用木马，你们有关于配置证书的链接指南吗？

**Comment by missuo** [comment]
> 非常感谢您的快速回复。V2ray是我的主要用途。以防万一我想使用木马，你们有关于配置证书的链接指南吗？

如果你知道原理，你就不会执着于Trojan。Trojan并不是一个很好的选择。配置起来会比较麻烦，而且TLS会增加延时。V2Ray目前使用的是AEAD，非常安全。


如果你坚持使用Trojan，你可以自行研究。请注意我不会提供任何方案，而且使用TLS意味着你必须有一个域名解析到你的IP。而并不是像你截图中的那样填写IP。

**Comment by GoodyOG** [comment]
谢谢。

**Comment by missuo** [comment]
> 谢谢。

That's what I'm supposed to do. You're welcome.
