### ISSUE TITLE
把 CF 的证书和 tls ws弄进脚本，不久一步到位了吗。

### ISSUE THREAD

**Issue by wg199** [missuo/XrayR-V2Board#16]

**Comment by missuo** [comment]
不一定大家都要用TLS的。

**Comment by wg199** [comment]
脚本嘛，集中一起方便，什么测速脚本，DD 脚本，bbr 脚本……一大堆，就想哪天有大佬出个大合集。

**Comment by missuo** [comment]
你要明白的事情是，写脚本很大一部分是作者自己为了方便。你们可以提出建议，但是最后作者会不会加上，还是取决于作者。因为开源本身就是一件慈善的事情，没有任何收益。加越多的功能必然会花费更多的时间，如果这个功能很少有人需要，就不可能去浪费这个时间。
