### ISSUE TITLE
No connection for people in China 

### ISSUE THREAD

**Issue by GoodyOG** [missuo/XrayR-V2Board#17]
the node isn't working for people in China. Any fix pls?

**Comment by missuo** [comment]
I hope you can bring the logs.

**Comment by GoodyOG** [comment]
`Aug 11 02:45:15 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:15 [Info] [389
3808151] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 154.89.5.216:42136 > common/drain: common/drain: unable to drain connection > read 
tcp 38.143.9.80:443->154.89.5.216:42136: i/o timeout > proxy/vmess/encoding: invalid us
er > proxy/vmess: Not Found
Aug 11 02:45:15 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:15 154.89.5.21
6:42136 rejected  common/drain: common/drain: unable to drain connection > read tcp 38.
143.9.80:443->154.89.5.216:42136: i/o timeout > proxy/vmess/encoding: invalid user > pr
oxy/vmess: Not Found
Aug 11 02:45:16 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:16 [Info] [179
9041477] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read r
equest header > EOF
Aug 11 02:45:20 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:20 [Info] [422
0496488] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 154.89.5.216:44360 > common/drain: common/drain: unable to drain connection > read 
tcp 38.143.9.80:443->154.89.5.216:44360: i/o timeout > proxy/vmess/encoding: invalid us
er > proxy/vmess: Not Found
Aug 11 02:45:20 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:20 154.89.5.21
6:44360 rejected  common/drain: common/drain: unable to drain connection > read tcp 38.
143.9.80:443->154.89.5.216:44360: i/o timeout > proxy/vmess/encoding: invalid user > pr
oxy/vmess: Not Found
Aug 11 02:45:24 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:24 [Info] [355
5074372] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 154.89.5.216:47120 > common/drain: common/drain: unable to drain connection > read 
tcp 38.143.9.80:443->154.89.5.216:47120: i/o timeout > proxy/vmess/encoding: invalid us
er > proxy/vmess: Not Found
Aug 11 02:45:24 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:24 154.89.5.21
6:47120 rejected  common/drain: common/drain: unable to drain connection > read tcp 38.
143.9.80:443->154.89.5.216:47120: i/o timeout > proxy/vmess/encoding: invalid user > pr
oxy/vmess: Not Found
Aug 11 02:45:27 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:27 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:45:28 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:28 [Info] [178
7669167] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 154.89.5.216:49122 > common/drain: common/drain: unable to drain connection > read 
tcp 38.143.9.80:443->154.89.5.216:49122: i/o timeout > proxy/vmess/encoding: invalid us
er > proxy/vmess: Not Found
Aug 11 02:45:28 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:28 154.89.5.21
6:49122 rejected  common/drain: common/drain: unable to drain connection > read tcp 38.
143.9.80:443->154.89.5.216:49122: i/o timeout > proxy/vmess/encoding: invalid user > pr
oxy/vmess: Not Found
Aug 11 02:45:33 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:33 [Info] [289
6810754] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 154.89.5.216:51290 > proxy/vmess/encoding: failed to read request header > read tcp
 38.143.9.80:443->154.89.5.216:51290: i/o timeout
Aug 11 02:45:33 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:33 154.89.5.21
6:51290 rejected  proxy/vmess/encoding: failed to read request header > read tcp 38.143
.9.80:443->154.89.5.216:51290: i/o timeout
Aug 11 02:45:37 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:37 [Info] [314
1664972] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 154.89.5.216:53706 > common/drain: common/drain: unable to drain connection > read 
tcp 38.143.9.80:443->154.89.5.216:53706: i/o timeout > proxy/vmess/encoding: invalid us
er > proxy/vmess: Not Found
Aug 11 02:45:37 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:45:37 154.89.5.21
6:53706 rejected  common/drain: common/drain: unable to drain connection > read tcp 38.
143.9.80:443->154.89.5.216:53706: i/o timeout > proxy/vmess/encoding: invalid user > pr
oxy/vmess: Not Found
Aug 11 02:46:28 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:46:28 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:47:30 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:47:30 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:48:31 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:48:31 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:49:02 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:49:02 [Info] [286
6443317] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request f
rom 91.191.209.182:61443 > common/drain: common/drain: unable to drain connection > rea
d tcp 38.143.9.80:443->91.191.209.182:61443: i/o timeout > proxy/vmess/encoding: invali
d user > proxy/vmess: Not Found
Aug 11 02:49:02 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:49:02 91.191.209.
182:61443 rejected  common/drain: common/drain: unable to drain connection > read tcp 3
8.143.9.80:443->91.191.209.182:61443: i/o timeout > proxy/vmess/encoding: invalid user 
> proxy/vmess: Not Found
Aug 11 02:49:32 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:49:32 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:50:33 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:50:33 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:51:34 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:51:34 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:52:35 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:52:35 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:53:37 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:53:37 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:54:37 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:54:37 [V2ray: 1] 
0 user deleted, 0 user added
Aug 11 02:55:38 GGCUS-43094-86682-wenboten XrayR[2245]: 2022/08/11 02:55:38 [V2ray: 1] 
0 user deleted, 0 user added I`

**Comment by missuo** [comment]
It looks like everything is fine, maybe the IP is blocked.

**Comment by GoodyOG** [comment]
Alright thnaks. Can you please recommend some client app on ios.

**Comment by missuo** [comment]
Surge、QuanX、Shadowrocket.

Shadowrocket is suitable for novices, Surge and QuanX are suitable for high-end users.  Compared to Surge, QuanX is more cost-effective.
