### ISSUE TITLE
启动不起来啊

### ISSUE THREAD

**Issue by tju-sun-lab** [missuo/XrayR-V2Board#21]
Sep 15 14:34:32 AMD2 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 15 14:34:32 AMD2 systemd[1]: XrayR.service: Failed with result 'exit-code'.
Sep 15 14:34:42 AMD2 systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Sep 15 14:34:42 AMD2 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 106.
Sep 15 14:34:42 AMD2 systemd[1]: Stopped XrayR Service.
Sep 15 14:34:42 AMD2 systemd[1]: Started XrayR Service.
Sep 15 14:34:42 AMD2 XrayR[609874]: XrayR 0.8.0 (A Xray backend that supports many panels)
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 Start the panel..
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 Xray Core Version: 1.5.4
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 [Debug] app/log: Logger started
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 [Info] app/dns: DNS: created localhost client
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 [Warning] core: Xray 1.5.4 started
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:80
Sep 15 14:34:42 AMD2 XrayR[609874]: 2022/09/15 14:34:42 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:80
Sep 15 14:34:43 AMD2 XrayR[609874]: panic: runtime error: index out of range [0] with length 0
Sep 15 14:34:43 AMD2 XrayR[609874]: goroutine 1 [running]:
Sep 15 14:34:43 AMD2 XrayR[609874]: github.com/XrayR-project/XrayR/service/controller.(*Controller).addNewUser(0xc0000cff40, 0xc0007e9128, 0xc0005cfd68?)
Sep 15 14:34:43 AMD2 XrayR[609874]:         github.com/XrayR-project/XrayR/service/controller/controller.go:339 +0x2cf
Sep 15 14:34:43 AMD2 XrayR[609874]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0000cff40)
Sep 15 14:34:43 AMD2 XrayR[609874]:         github.com/XrayR-project/XrayR/service/controller/controller.go:64 +0x2a9
Sep 15 14:34:43 AMD2 XrayR[609874]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000146f00)
Sep 15 14:34:43 AMD2 XrayR[609874]:         github.com/XrayR-project/XrayR/panel/panel.go:192 +0x59a
Sep 15 14:34:43 AMD2 XrayR[609874]: main.main()
Sep 15 14:34:43 AMD2 XrayR[609874]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Sep 15 14:34:43 AMD2 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 15 14:34:43 AMD2 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by missuo** [comment]
给我看看你的配置文件。

**Comment by missuo** [comment]
```shell
cat /etc/XrayR/config.conf
```

**Comment by tju-sun-lab** [comment]
Log:
  Level: debug # Log level: none, error, warning, info, debug 
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath: # ./dns.json Path to dns config 
Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: "https://board.xxxxx.tk" # 修改这里
      ApiKey: "0xxxxxxxf0x5fxxxxxdf" # 修改这里
      NodeID: 1
      NodeType: V2ray
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type, Remote configuration first
      EnableXTLS: false # Enable XTLS for V2ray and Trojan, emote configuration first
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by tju-sun-lab** [comment]
换了个ubuntu服务器也是一样问题

**Comment by missuo** [comment]
你开TLS了吗？

**Comment by tju-sun-lab** [comment]
没开TLS

**Comment by missuo** [comment]
> 没开TLS

面板配置截图看看

**Comment by tju-sun-lab** [comment]
<img width="392" alt="微信截图_20220916102644" src="https://user-images.githubusercontent.com/100348287/190543401-97a23d9f-3633-47fc-873b-2a98e2a1b970.png">

**Comment by missuo** [comment]
看下来没什么问题，有没有可能是你user权限组下面没有用户呢？
