### ISSUE TITLE
手动数据库更改站点上的问题

### ISSUE THREAD

**Issue by msaebi031** [missuo/XrayR-V2Board#25]
我手动更改了数据库并遇到了这个问题
我什至重置了它，但问题仍然存在
但它似乎被锁定，所以它不起作用
你能告诉我问题所在吗？
![image](https://github.com/missuo/XrayR-V2Board/assets/44286111/b97285e7-6bd5-4db1-90f2-ee1b02bad728)

**Comment by missuo** [comment]
That doesn't seem to be the scope of what I'm dealing with. This has nothing to do with the script I provided. @msaebi031

**Comment by msaebi031** [comment]
请告诉我为什么会这样，我该怎么办
请

**Comment by missuo** [comment]
This REPO prohibits asking any unrelated questions, sorry.
