### ISSUE TITLE
节点是黄色，测试延迟-1

### ISSUE THREAD

**Issue by Simonaorg** [missuo/XrayR-V2Board#26]
大多数按照教程配置的，除了v2board 面板添加时，连接端口和服务端口填的的端口号不一样，尝试过把连接端口和服务端口的端口号填同一个数字，XrayR 不能启动。

配置文件：
Log:
  Level: debug # Log level: none, error, warning, info, debug 
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath: # ./dns.json Path to dns config 
Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: "https://fmywebsite.com" # 修改这里
      ApiKey: "Myapikey" # 修改这里
      NodeID: 1
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type, Remote configuration first
      EnableXTLS: false # Enable XTLS for V2ray and Trojan, emote configuration first
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      CertConfig:
        CertMode: file # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/ssl/private/fullchain.pem # Provided if the CertMode is file
        KeyFile: /etc/ssl/private/privkey.pem
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by missuo** [comment]
黄色代表节点正常。自行查找问题。
