### ISSUE TITLE
为什么默认关闭AEAD？

### ISSUE THREAD

**Issue by kfcceo** [missuo/XrayR-V2Board#5]

**Comment by kfcceo** [comment]
为什么要取消AEAD加密？现在不都是增加AEAD加密机制避免被探测到吗？

**Comment by missuo** [comment]
这是本脚本可以选择的，您可以自行选择关闭或者开启。我默认提供关闭是因为之前Shadowrocket、QuanX这些软件没有支持AEAD。直到目前OpenWRT的App也没有支持AEAD，我是软路由的重度用户，为了保证软路由的可用性，我提供的脚本默认关闭AEAD，您可以修改`install.sh`文件的193行为1即可默认开启AEAD加密。

**Comment by missuo** [comment]
已修改为默认开启。
https://github.com/missuo/XrayR-V2Board/blob/main/README.md#2022%E5%B9%B42%E6%9C%8828%E6%97%A5

**Comment by kfcceo** [comment]
多谢大神耐心解答

Vincent Young ***@***.***> 于2022年2月22日周二 21:18写道：
