### ISSUE TITLE
使用指南中提到的信息错误

### ISSUE THREAD

**Issue by Xiaodu233** [missuo/XrayR-V2Board#7]
在“2.修改 install.sh 文件的169行，将用户名 missuo 修改为你自己的GitHub用户名。
wget https://cdn.jsdelivr.net/gh/missuo/XrayR-V2Board/config.yml -O /etc/XrayR/config.yml“
这一步中，命令行的位置在第203行，而非第1第96行。
另外，文件中有多处包含您用户名的链接，是否需要改动？

**Comment by missuo** [comment]
谢谢反馈，确实在203行，脚本我改过了没注意。别的地方无需改动

**Comment by Xiaodu233** [comment]
谢谢回复
