### ISSUE TITLE
app/proxyman/inbound: connection ends > proxy/trojan: invalid protocol or invalid user

### ISSUE THREAD

**Issue by AngelaZhangyu** [missuo/XrayR-V2Board#9]
部署完毕后，用v2rayN访问会出现app/proxyman/inbound: connection ends > proxy/trojan: invalid protocol or invalid user，但是用v2rayU客户端就可以访问。请问如何解决呢？

**Comment by missuo** [comment]
应该不是我脚本的问题。可能是v2rayN版本太老，不支持AEAD加密。

**Comment by AngelaZhangyu** [comment]
> 

我用最新的5.22 v2rayN也是不行。

**Comment by missuo** [comment]
那就不知道了我这边还是建议你用Clash。
> > 
> 
> 
> 
> 我用最新的5.22 v2rayN也是不行。
